services:
  minio:
    image: minio/minio:latest
    container_name: advanced-eda-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: adminpass
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: adminuser
      MINIO_ROOT_PASSWORD: adminpass
    entrypoint: >
      /bin/sh -c "
        set -e;
        until mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
        do
          sleep 2;
        done;
        echo 'MinIO is ready. Use the mc container to manage buckets.';
        tail -f /dev/null
      "
